### PR TITLE
scripts: modify script to push kube-etcd-signer-server and kube-client-agent images

### PR DESCRIPTION
**Pull request by rithujohn191**
This allows Travis CI to push kube-etcd-signer-server and kube-client-agent images to quay

### CODE REVIEW

**Review by ericchiang — APPROVED** [review]
lgtm, thanks!

**Comment by ericchiang** [comment]
@rithujohn191 I don't think this worked

```
Removing intermediate container bc0bf7ba7728
Successfully built 9118009374de
Successfully tagged quay.io/coreos/kube-etcd-signer-server:a88fa11e0e520d9b280c43bfef1802cfa9829ee0
The push refers to a repository [quay.io/coreos/kube-etcd-signer-server]
a9de20b4874d: Preparing
e53f74215d12: Preparing
unauthorized: access to the requested resource is not authorized
make: *** [push/kube-etcd-signer-server] Error 1
```

https://travis-ci.org/coreos/kubecsr/builds/347046184#L740

**Comment by ericchiang** [comment]
Can you move the after_success target to the regular script step? I'd like the build to go red if that step fails https://github.com/coreos/kubecsr/blob/a88fa11e0e520d9b280c43bfef1802cfa9829ee0/.travis.yml#L11

**Comment by rithujohn191** [comment]
https://travis-ci.org/coreos/kubecsr/builds/347046184

Latest build passed...it was a permission issue....will move the after_success target to the regular script step in another PR

**Pull request merged**
