### PR TITLE
*: improve retry logic and defaults

### PR DESCRIPTION
**Pull request by hexfusion**
The current default of 0 Steps is causing instant exit. This PR sets the default and minimum to 1.

/cc @wking @abhinavdahiya

### CODE REVIEW

**Comment by wking** [comment]
I'd have expected a zero default with "retry forever" semantics.  Does that seem feasible?

**Comment by hexfusion** [comment]
> I'd have expected a zero default with "retry forever" semantics. Does that seem feasible?

@wking yes that makes sense to me updated.


@abhinavdahiya OK, now we retry forever by default thoughts?

**Comment by hexfusion** [comment]
bah thats not right... resolving.

**Comment by hexfusion** [comment]
OK I think that is sane

**Comment by wking** [comment]
Carried in #27.

**Pull request closed without merging**
